version: 2
jobs:
  build:
    working_directory: ../html
    docker:
      - image: node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - public
  deploy:
    working_directory: ../html
    docker:
      - image: node:10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "$GITHUB_EMAIL"
            git config --global user.name "$GITHUB_USERNAME"
            git remote add deploy "https://$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/$GITHUB_REPO.git"
            git checkout -b gh-pages
            git add -f public
            git commit -m "Deploy $(date)"
            git push deploy gh-pages:gh-pages --force

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master